# Generated by Django 5.1.1 on 2024-10-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='توضیح خلاصه دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default='توضیح خلاصه زیر دسته بندی'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='subcategories/default.jpg', upload_to='subcategories'),
        ),
    ]
