# Generated by Django 5.1.1 on 2024-10-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subcategory'),
        ),
    ]
